sudo: required

arch:
- arm64
- amd64

services:
- docker

script:
  - docker build -t abhishek138/maven-resource:latest .
  - docker login -u abhishek138 -p abhishek138
  - docker push abhishek138/maven-resource:latest
